import './globals.css'
import { cn } from '@/lib/utilities'
import { CustomLayout } from '@/components/CustomLayout'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn(
        'min-h-screen antialiased'
      )}
      >
        <CustomLayout>
          {children}
        </CustomLayout>
      </body>
    </html>
  )
}
